//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKAN.Collaborator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblActivity
    {
        public int ID { get; set; }
        public int ActivityNames_ID { get; set; }
        public string IPAddress { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> Collaborator_ID { get; set; }
        public Nullable<int> Box_ID { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public string Status_Name { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
        public Nullable<int> Ver { get; set; }
    
        public virtual TblActivityName TblActivityName { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
