//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKAN.Collaborator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUser()
        {
            this.TblCollaborators = new HashSet<TblCollaborator>();
            this.TblActivities = new HashSet<TblActivity>();
        }
    
        public int ID { get; set; }
        public string EMail { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> License_Allowed { get; set; }
        public Nullable<int> License_Total { get; set; }
        public Nullable<int> User_Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCollaborator> TblCollaborators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblActivity> TblActivities { get; set; }
    }
}
